#!/bin/sh
# Run tests and type checks before pushing
pytest
status=$?
if [ $status -ne 0 ]; then
  echo "\nTests failed. Aborting push." >&2
  exit $status
fi

mypy goal_glide
status=$?
if [ $status -ne 0 ]; then
  echo "\nType checks failed. Aborting push." >&2
  exit $status
fi
