[tool.black]
target-version = ['py311']

[tool.ruff]

[tool.mypy]
python_version = '3.11'
strict = true
ignore_missing_imports = true

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "goal_glide"
version = "0.0.0"
dependencies = [
    "textual>=0.55",
    "jinja2>=3.1",
    "pandas>=2.0",
]
